services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    volumes:
      - ./app:/app
      - /app/node_modules/
    depends_on:
      - api

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - ./api:/api
      - /api/node_modules/
    depends_on:
      - db

  db:
    image: mongo
    volumes:
      - ./db:/data/db

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "80:80"
    depends_on:
      - app
      - api
