# --- Dependencies --- #
FROM node:16-alpine AS dependencies
WORKDIR /app

COPY package*.json ./

RUN npm ci

# --- Run --- #
FROM node:16-alpine AS run
WORKDIR /app

COPY --from=dependencies /app/node_modules/ node_modules/

EXPOSE 3000
CMD ["node_modules/.bin/next", "dev"]