# --- Dependencies --- #
FROM node:16-alpine AS dependencies
WORKDIR /api

COPY package*.json ./

RUN npm ci

# --- Run --- #
FROM node:16-alpine AS run
WORKDIR /api

COPY --from=dependencies /api/node_modules/ node_modules/

EXPOSE 3000
CMD ["npm", "run", "dev"]